import type { Course, Lesson } from "./types";

const beginnerLessons: Lesson[] = [
  {
    id: "lesson-variables",
    courseId: "python-beginner",
    slug: "variables",
    title: "Variables and Values",
    summary: "Store names, numbers, and results in variables.",
    prompt: "Build a short learner profile that stores a name, age, school, and one learning goal, then prints a friendly summary.",
    expectedConcepts: ["variables", "strings", "numbers", "print"],
    starterCode: "name = \"Amina\"\nage = 13\nschool = \"Demo School\"\ngoal = \"learn Python\"\n\n# Print a profile summary below\n",
    visibleTests: ["Output includes the learner name", "Output includes one number", "Code uses at least three variables"],
    reflectionPrompts: ["Which variable was easiest to explain?", "How would you rename one variable to make the program clearer?"],
    teacherNotes: "Look for meaningful variable names and evidence that students understand assignment versus printing.",
  },
  {
    id: "lesson-strings",
    courseId: "python-beginner",
    slug: "strings",
    title: "Strings and Messages",
    summary: "Join text, format messages, and make output readable.",
    prompt: "Create a welcome card for a new coding club member using their name, school, and favorite subject.",
    expectedConcepts: ["strings", "f-string", "concatenation", "print"],
    starterCode: "name = \"Amina\"\nschool = \"Demo School\"\nsubject = \"science\"\n\n# Build and print a welcome message\n",
    visibleTests: ["Uses at least three text values", "Prints a complete sentence", "Includes the learner name"],
    reflectionPrompts: ["What makes the message easy to read?", "Where did formatting help you avoid repeated text?"],
    teacherNotes: "Look for students using variables inside the message rather than hard-coding the whole sentence.",
  },
  {
    id: "lesson-numbers",
    courseId: "python-beginner",
    slug: "numbers",
    title: "Numbers and Calculations",
    summary: "Use arithmetic to solve everyday problems.",
    prompt: "Calculate the total cost of exercise books, pens, and transport for a school day, then print the final total.",
    expectedConcepts: ["integers", "addition", "multiplication", "variables"],
    starterCode: "book_price = 2500\nbooks = 3\npen_price = 500\npens = 2\ntransport = 2000\n\n# Calculate the total cost\n",
    visibleTests: ["Uses multiplication", "Calculates a total", "Prints a number"],
    reflectionPrompts: ["Which value would change most often in real life?", "How could a wrong total happen?"],
    teacherNotes: "Use this lesson to discuss numeric types and why variable names matter in calculations.",
  },
  {
    id: "lesson-input-output",
    courseId: "python-beginner",
    slug: "input-output",
    title: "Input and Output",
    summary: "Ask for user input and respond clearly.",
    prompt: "Build a simple greeting program that asks for a name and favorite subject, then prints a personal message.",
    expectedConcepts: ["input", "strings", "f-string", "print"],
    starterCode: "name = input(\"What is your name? \")\nsubject = input(\"Favorite subject? \")\n\n# Print a personal message\n",
    visibleTests: ["Uses input twice", "Uses both answers in output", "Output is friendly and clear"],
    reflectionPrompts: ["What could confuse a user of your program?", "How could you improve one prompt?"],
    teacherNotes: "In browser execution, input may be simulated or discussed depending on device constraints.",
  },
  {
    id: "lesson-booleans",
    courseId: "python-beginner",
    slug: "booleans-comparisons",
    title: "Booleans and Comparisons",
    summary: "Compare values and store true or false results.",
    prompt: "Check whether a learner has reached a practice goal by comparing minutes practiced with a target.",
    expectedConcepts: ["booleans", "comparison", "greater than", "print"],
    starterCode: "minutes_practiced = 35\ntarget_minutes = 30\n\n# Compare practice time with the target\n",
    visibleTests: ["Uses a comparison operator", "Stores or prints a boolean result", "Mentions the target"],
    reflectionPrompts: ["What does True mean in your program?", "What boundary value should you test?"],
    teacherNotes: "Make sure learners understand that comparisons produce values that programs can use later.",
  },
  {
    id: "lesson-conditionals",
    courseId: "python-beginner",
    slug: "conditionals",
    title: "Conditionals",
    summary: "Make decisions with if, elif, and else.",
    prompt: "Write a small study helper that recommends what a learner should do based on their quiz score.",
    expectedConcepts: ["if", "elif", "else", "comparison"],
    starterCode: "score = 72\n\n# Recommend next steps for the learner\n",
    visibleTests: ["Uses if or elif", "Handles high, medium, and low scores", "Prints a recommendation"],
    reflectionPrompts: ["What score ranges did you choose?", "What happens exactly at the boundary between two ranges?"],
    teacherNotes: "Ask students to justify their thresholds before they code.",
  },
  {
    id: "lesson-nested-conditionals",
    courseId: "python-beginner",
    slug: "nested-conditionals",
    title: "Nested Decisions",
    summary: "Combine more than one decision carefully.",
    prompt: "Recommend a learning activity based on a student's quiz score and whether they have internet access today.",
    expectedConcepts: ["nested if", "and", "else", "decision tree"],
    starterCode: "score = 64\nhas_internet = True\n\n# Recommend an activity\n",
    visibleTests: ["Uses more than one condition", "Handles internet and no-internet cases", "Prints one clear recommendation"],
    reflectionPrompts: ["Which decision should happen first?", "How did you avoid contradictory recommendations?"],
    teacherNotes: "Encourage learners to sketch the decision tree before writing nested code.",
  },
  {
    id: "lesson-lists",
    courseId: "python-beginner",
    slug: "lists",
    title: "Lists",
    summary: "Collect related values and work through them.",
    prompt: "Track a learner's three recent quiz scores, calculate the total, and print a short progress message.",
    expectedConcepts: ["list", "sum", "len", "loop or indexing"],
    starterCode: "scores = [68, 74, 81]\n\n# Calculate total and average\n",
    visibleTests: ["Uses a list", "Calculates an average", "Prints a progress message"],
    reflectionPrompts: ["What changes if there are five scores?", "Why is a list better than three separate variables here?"],
    teacherNotes: "Encourage students to use len(scores), not a hard-coded count.",
  },
  {
    id: "lesson-indexing",
    courseId: "python-beginner",
    slug: "indexing",
    title: "Indexing and Slicing",
    summary: "Find and extract items from ordered data.",
    prompt: "Use a list of school subjects to print the first subject, last subject, and a short list of revision priorities.",
    expectedConcepts: ["index", "slice", "list", "negative index"],
    starterCode: "subjects = [\"math\", \"english\", \"science\", \"history\", \"python\"]\n\n# Print selected subjects\n",
    visibleTests: ["Uses an index", "Uses a slice", "Prints more than one selection"],
    reflectionPrompts: ["Why does the first item use index 0?", "What slice would you use for the first three subjects?"],
    teacherNotes: "This lesson is a good place to catch off-by-one misunderstandings.",
  },
  {
    id: "lesson-list-methods",
    courseId: "python-beginner",
    slug: "list-methods",
    title: "List Methods",
    summary: "Add, remove, and sort items in a list.",
    prompt: "Maintain a classroom supply list by adding a missing item, removing a duplicate, and printing the sorted list.",
    expectedConcepts: ["append", "remove", "sort", "list methods"],
    starterCode: "supplies = [\"chalk\", \"books\", \"pens\", \"books\"]\n\n# Update and print the supply list\n",
    visibleTests: ["Adds one item", "Removes one duplicate or unwanted item", "Sorts or clearly prints the final list"],
    reflectionPrompts: ["Which method changed the list?", "What would happen if the item to remove was missing?"],
    teacherNotes: "Discuss methods as actions that belong to a data type.",
  },
  {
    id: "lesson-loops",
    courseId: "python-beginner",
    slug: "loops",
    title: "Loops",
    summary: "Repeat useful work without copying code.",
    prompt: "Create a weekly practice planner that prints a small Python practice task for each school day.",
    expectedConcepts: ["for loop", "list", "print"],
    starterCode: "days = [\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\"]\n\n# Print a practice plan for each day\n",
    visibleTests: ["Uses a loop", "Prints at least five lines", "Mentions each day"],
    reflectionPrompts: ["What repeated pattern did the loop remove?", "How would you add Saturday practice?"],
    teacherNotes: "Help learners see loops as a way to represent a pattern, not just a syntax requirement.",
  },
  {
    id: "lesson-loop-accumulators",
    courseId: "python-beginner",
    slug: "loop-accumulators",
    title: "Loop Accumulators",
    summary: "Build totals while a loop runs.",
    prompt: "Add up weekly study minutes from a list and print the total plus the average per day.",
    expectedConcepts: ["for loop", "accumulator", "total", "average"],
    starterCode: "minutes = [20, 30, 25, 40, 35]\ntotal = 0\n\n# Add each day's minutes to total\n",
    visibleTests: ["Uses a loop to build a total", "Calculates an average", "Prints total and average"],
    reflectionPrompts: ["Why did total start at 0?", "What changes if one more day is added?"],
    teacherNotes: "Focus on tracing the value of the accumulator after each loop pass.",
  },
  {
    id: "lesson-while-loops",
    courseId: "python-beginner",
    slug: "while-loops",
    title: "While Loops",
    summary: "Repeat until a condition changes.",
    prompt: "Simulate a savings goal where a learner adds the same amount each week until they can buy a calculator.",
    expectedConcepts: ["while loop", "condition", "counter", "accumulator"],
    starterCode: "goal = 15000\nsaved = 0\nweekly_saving = 3000\nweeks = 0\n\n# Keep saving until the goal is reached\n",
    visibleTests: ["Uses a while loop", "Updates saved amount", "Prints number of weeks"],
    reflectionPrompts: ["What condition stops the loop?", "What bug could make this loop never end?"],
    teacherNotes: "Require learners to identify the changing variable that eventually ends the loop.",
  },
  {
    id: "lesson-functions",
    courseId: "python-beginner",
    slug: "functions",
    title: "Functions",
    summary: "Name reusable steps and pass information into them.",
    prompt: "Write a function that creates a revision message for any subject and number of minutes.",
    expectedConcepts: ["def", "parameters", "return", "function call"],
    starterCode: "def revision_message(subject, minutes):\n    # Return a helpful message\n    return \"\"\n\nprint(revision_message(\"math\", 20))\n",
    visibleTests: ["Defines a function", "Uses at least two parameters", "Calls the function"],
    reflectionPrompts: ["Why is this better as a function?", "What input would you test next?"],
    teacherNotes: "A good answer separates the message pattern from one specific example.",
  },
  {
    id: "lesson-function-return-values",
    courseId: "python-beginner",
    slug: "function-return-values",
    title: "Return Values",
    summary: "Return results so other code can use them.",
    prompt: "Write a function that calculates the average of three quiz scores and returns the result for a progress message.",
    expectedConcepts: ["return", "function call", "average", "variable assignment"],
    starterCode: "def average_score(score1, score2, score3):\n    # Calculate and return the average\n    return 0\n\naverage = average_score(70, 82, 76)\n# Print a progress message\n",
    visibleTests: ["Returns a calculated value", "Stores the returned value", "Prints the average"],
    reflectionPrompts: ["Why return instead of only printing?", "How could this function handle more scores later?"],
    teacherNotes: "Distinguish between output for humans and returned values for the program.",
  },
  {
    id: "lesson-dictionaries",
    courseId: "python-beginner",
    slug: "dictionaries",
    title: "Dictionaries",
    summary: "Store labeled information with keys and values.",
    prompt: "Create a learner profile dictionary with name, school, class level, and learning goal, then print a clear summary.",
    expectedConcepts: ["dictionary", "keys", "values", "lookup"],
    starterCode: "learner = {\n    \"name\": \"Amina\",\n    \"school\": \"Demo School\",\n    \"level\": \"S1\",\n    \"goal\": \"learn Python\"\n}\n\n# Print a profile summary\n",
    visibleTests: ["Uses a dictionary", "Looks up at least two keys", "Prints a readable summary"],
    reflectionPrompts: ["Why are keys useful?", "What key would you add next?"],
    teacherNotes: "Connect dictionaries to real forms and records students already understand.",
  },
  {
    id: "lesson-dictionary-updates",
    courseId: "python-beginner",
    slug: "dictionary-updates",
    title: "Updating Dictionaries",
    summary: "Change, add, and read dictionary values.",
    prompt: "Update a small inventory dictionary after a classroom receives new pens and uses some books.",
    expectedConcepts: ["dictionary update", "assignment", "keys", "arithmetic"],
    starterCode: "inventory = {\n    \"pens\": 12,\n    \"books\": 8,\n    \"chalk\": 4\n}\n\n# Update the inventory and print the result\n",
    visibleTests: ["Updates an existing key", "Adds or changes a quantity", "Prints final inventory"],
    reflectionPrompts: ["Which value changed and why?", "How could you prevent a negative quantity?"],
    teacherNotes: "Use this lesson to reinforce mutation and careful arithmetic with stored values.",
  },
  {
    id: "lesson-debugging",
    courseId: "python-beginner",
    slug: "debugging",
    title: "Debugging",
    summary: "Read errors and test assumptions one step at a time.",
    prompt: "Fix a broken points calculator and explain which bug you found first.",
    expectedConcepts: ["syntax errors", "logic errors", "print debugging"],
    starterCode: "points = [10, 8, 7]\nbonus = 5\n\n# This should print the total points with bonus.\ntotal = sum(points) + bonus\nprint(\"Total:\", total)\n",
    visibleTests: ["Program runs without errors", "Total includes all points", "Student explains one bug"],
    reflectionPrompts: ["What clue helped you find the issue?", "What test would catch this bug again?"],
    teacherNotes: "Require students to name the evidence they used, not only the final fix.",
  },
  {
    id: "lesson-error-handling",
    courseId: "python-beginner",
    slug: "error-handling",
    title: "Handling Bad Input",
    summary: "Plan for input that may be missing or invalid.",
    prompt: "Write a score checker that handles a score below 0 or above 100 with a helpful message.",
    expectedConcepts: ["validation", "if", "elif", "boundary"],
    starterCode: "score = 105\n\n# Check whether the score is valid before giving feedback\n",
    visibleTests: ["Checks for invalid low scores", "Checks for invalid high scores", "Prints helpful feedback"],
    reflectionPrompts: ["Which invalid input did you protect against?", "Why check validity before feedback?"],
    teacherNotes: "This prepares students for robust programs without needing exceptions yet.",
  },
  {
    id: "lesson-testing",
    courseId: "python-beginner",
    slug: "testing",
    title: "Manual Testing",
    summary: "Choose examples that prove code works.",
    prompt: "Create a small set of test cases for a grade feedback program and print what each case should check.",
    expectedConcepts: ["test cases", "boundary values", "expected output", "conditionals"],
    starterCode: "test_scores = [0, 49, 50, 79, 80, 100]\n\n# Print what each score should test\n",
    visibleTests: ["Includes boundary values", "Explains expected behavior", "Uses more than one test case"],
    reflectionPrompts: ["Which test is most likely to catch a bug?", "What case did you almost forget?"],
    teacherNotes: "Make testing a reasoning habit before automated test syntax is introduced.",
  },
  {
    id: "lesson-modules-random",
    courseId: "python-beginner",
    slug: "modules-random",
    title: "Modules and Random Choices",
    summary: "Use built-in modules to add useful behavior.",
    prompt: "Create a study prompt generator that randomly chooses a subject and a short practice task.",
    expectedConcepts: ["import", "random", "choice", "list"],
    starterCode: "import random\n\nsubjects = [\"math\", \"science\", \"english\", \"python\"]\ntasks = [\"review notes\", \"answer 5 questions\", \"teach a friend\"]\n\n# Choose and print a random study prompt\n",
    visibleTests: ["Imports random", "Uses random.choice", "Prints a subject and task"],
    reflectionPrompts: ["What changes each time the program runs?", "When is randomness useful in learning software?"],
    teacherNotes: "Discuss modules as reusable tools written by others.",
  },
  {
    id: "lesson-files-concept",
    courseId: "python-beginner",
    slug: "files-concept",
    title: "File Thinking",
    summary: "Understand how programs save and read information.",
    prompt: "Design a reading log as a list of lines, then print it as if it were saved in a text file.",
    expectedConcepts: ["strings", "lists", "join", "file concept"],
    starterCode: "reading_log = [\n    \"Monday: 10 pages\",\n    \"Tuesday: 12 pages\",\n    \"Wednesday: 8 pages\"\n]\n\n# Format the log for saving or display\n",
    visibleTests: ["Uses multiple lines of text", "Formats a readable log", "Mentions saving or displaying"],
    reflectionPrompts: ["Why might a program save this information?", "What would each line in a file represent?"],
    teacherNotes: "Browser constraints may limit real file access, so teach the model before real file I/O.",
  },
  {
    id: "project-study-timer",
    courseId: "python-beginner",
    slug: "study-timer",
    title: "Project: Study Timer",
    summary: "Plan focused practice blocks.",
    prompt: "Create a study timer planner that takes subjects and minutes, then prints a balanced revision schedule.",
    expectedConcepts: ["lists", "loops", "conditionals", "functions"],
    starterCode: "subjects = [\"math\", \"science\", \"python\"]\nminutes_each = 20\n\n# Build a schedule\n",
    visibleTests: ["Uses a loop", "Mentions all subjects", "Includes total minutes"],
    reflectionPrompts: ["How did you decide the schedule order?", "What would make this more useful in your school week?"],
    teacherNotes: "A strong project has clear output and avoids repeating print statements manually.",
  },
  {
    id: "project-market-calculator",
    courseId: "python-beginner",
    slug: "market-calculator",
    title: "Project: Market Calculator",
    summary: "Use Python to total everyday purchases.",
    prompt: "Build a small calculator for a market basket with item names, prices, and a total cost.",
    expectedConcepts: ["lists", "numbers", "loops", "formatting"],
    starterCode: "items = [\"beans\", \"rice\", \"soap\"]\nprices = [3500, 4200, 2500]\n\n# Print each item and the total\n",
    visibleTests: ["Prints every item", "Calculates total from prices", "Uses clear currency output"],
    reflectionPrompts: ["Where could a wrong total come from?", "How would you add one more item?"],
    teacherNotes: "The local context makes this a useful discussion of data representation and careful totals.",
  },
  {
    id: "project-quiz-game",
    courseId: "python-beginner",
    slug: "quiz-game",
    title: "Project: Quiz Game",
    summary: "Combine decisions, scorekeeping, and feedback.",
    prompt: "Create a three-question quiz that tracks a score and prints encouraging feedback.",
    expectedConcepts: ["variables", "conditionals", "scorekeeping", "functions"],
    starterCode: "score = 0\n\n# Ask or simulate three questions, update score, and print feedback\n",
    visibleTests: ["Tracks a score", "Has three questions or checks", "Prints final feedback"],
    reflectionPrompts: ["Which part controls the score?", "How could you make the quiz fairer?"],
    teacherNotes: "If input is awkward on school devices, let learners simulate answers with variables first.",
  },
  {
    id: "project-attendance-summary",
    courseId: "python-beginner",
    slug: "attendance-summary",
    title: "Project: Attendance Summary",
    summary: "Summarize class attendance data.",
    prompt: "Create a program that counts present and absent learners from a list and prints an attendance summary.",
    expectedConcepts: ["lists", "loops", "counters", "conditionals"],
    starterCode: "attendance = [\"present\", \"absent\", \"present\", \"present\", \"absent\"]\n\n# Count present and absent learners\n",
    visibleTests: ["Counts present learners", "Counts absent learners", "Prints a clear summary"],
    reflectionPrompts: ["What data representation did you choose?", "How would a teacher use this summary?"],
    teacherNotes: "This project reinforces accumulators and conditionals with familiar classroom data.",
  },
  {
    id: "project-library-helper",
    courseId: "python-beginner",
    slug: "library-helper",
    title: "Project: Library Helper",
    summary: "Search and summarize simple library records.",
    prompt: "Build a helper that stores book titles and availability, then prints which books can be borrowed.",
    expectedConcepts: ["dictionaries", "loops", "conditionals", "lists"],
    starterCode: "books = {\n    \"Python Basics\": True,\n    \"Science Stories\": False,\n    \"Math Practice\": True\n}\n\n# Print available books\n",
    visibleTests: ["Uses a dictionary", "Checks availability", "Prints only or clearly marks available books"],
    reflectionPrompts: ["Why is a dictionary useful here?", "What information would a real library system need?"],
    teacherNotes: "Use this to connect data structures to simple information systems.",
  },
  {
    id: "project-health-reminder",
    courseId: "python-beginner",
    slug: "health-reminder",
    title: "Project: Health Reminder",
    summary: "Generate helpful reminders from simple rules.",
    prompt: "Create a daily health reminder that uses weather, water intake, and activity minutes to suggest one action.",
    expectedConcepts: ["conditionals", "booleans", "functions", "messages"],
    starterCode: "weather = \"hot\"\nglasses_of_water = 3\nactivity_minutes = 20\n\n# Print one helpful health reminder\n",
    visibleTests: ["Uses at least two inputs", "Uses conditionals", "Prints one practical reminder"],
    reflectionPrompts: ["Which condition matters most?", "How could the reminder avoid being confusing?"],
    teacherNotes: "Encourage learners to keep advice simple and safe, not medical.",
  },
  {
    id: "project-budget-planner",
    courseId: "python-beginner",
    slug: "budget-planner",
    title: "Project: Budget Planner",
    summary: "Compare income, spending, and savings.",
    prompt: "Build a weekly budget planner that totals income and expenses, then says whether the learner met a savings goal.",
    expectedConcepts: ["lists", "sum", "conditionals", "formatting"],
    starterCode: "income = [5000, 3000]\nexpenses = [2500, 1000, 1500]\nsavings_goal = 2500\n\n# Calculate remaining money and compare with the goal\n",
    visibleTests: ["Totals income", "Totals expenses", "Compares remaining money with a goal"],
    reflectionPrompts: ["What assumption did your budget make?", "Which value would you test at the boundary?"],
    teacherNotes: "Good capstone for arithmetic, lists, and conditional feedback.",
  },
  {
    id: "project-final-learning-coach",
    courseId: "python-beginner",
    slug: "final-learning-coach",
    title: "Capstone: Learning Coach",
    summary: "Combine the course into one useful study assistant.",
    prompt: "Create a study coach that stores subjects and scores, recommends what to revise first, and prints a weekly practice plan.",
    expectedConcepts: ["lists", "dictionaries", "loops", "functions", "conditionals"],
    starterCode: "subjects = [\n    {\"name\": \"math\", \"score\": 62},\n    {\"name\": \"science\", \"score\": 78},\n    {\"name\": \"python\", \"score\": 70}\n]\n\n# Recommend a revision plan\n",
    visibleTests: ["Uses structured data", "Uses a function or loop", "Recommends a subject to revise", "Prints a weekly plan"],
    reflectionPrompts: ["How did your program choose the priority subject?", "What would you improve if another student used it?"],
    teacherNotes: "Assess decomposition, clarity, and whether the student can justify decisions from data.",
  },
];

export const courses: Course[] = [
  {
    id: "python-beginner",
    title: "Python Beginner Track",
    description: "A school-ready Python curriculum built around specification, dialogue, code, and reflection.",
    lessons: beginnerLessons,
  },
];

export function getLesson(lessonId: string): Lesson | undefined {
  return courses.flatMap((course) => course.lessons).find((lesson) => lesson.id === lessonId);
}

export function getDefaultLesson(): Lesson {
  return beginnerLessons[0];
}
