import type { Course, Lesson } from "./types";

const beginnerLessons: Lesson[] = [
  {
    id: "lesson-variables",
    courseId: "python-beginner",
    slug: "variables",
    title: "Variables and Values",
    summary: "Store names, numbers, and results in variables.",
    prompt: "Build a short learner profile that stores a name, age, school, and one learning goal, then prints a friendly summary.",
    expectedConcepts: ["variables", "strings", "numbers", "print"],
    starterCode: "name = \"Amina\"\nage = 13\nschool = \"Demo School\"\ngoal = \"learn Python\"\n\n# Print a profile summary below\n",
    visibleTests: ["Output includes the learner name", "Output includes one number", "Code uses at least three variables"],
    reflectionPrompts: ["Which variable was easiest to explain?", "How would you rename one variable to make the program clearer?"],
    teacherNotes: "Look for meaningful variable names and evidence that students understand assignment versus printing.",
  },
  {
    id: "lesson-conditionals",
    courseId: "python-beginner",
    slug: "conditionals",
    title: "Conditionals",
    summary: "Make decisions with if, elif, and else.",
    prompt: "Write a small study helper that recommends what a learner should do based on their quiz score.",
    expectedConcepts: ["if", "elif", "else", "comparison"],
    starterCode: "score = 72\n\n# Recommend next steps for the learner\n",
    visibleTests: ["Uses if or elif", "Handles high, medium, and low scores", "Prints a recommendation"],
    reflectionPrompts: ["What score ranges did you choose?", "What happens exactly at the boundary between two ranges?"],
    teacherNotes: "Ask students to justify their thresholds before they code.",
  },
  {
    id: "lesson-loops",
    courseId: "python-beginner",
    slug: "loops",
    title: "Loops",
    summary: "Repeat useful work without copying code.",
    prompt: "Create a weekly practice planner that prints a small Python practice task for each school day.",
    expectedConcepts: ["for loop", "list", "print"],
    starterCode: "days = [\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\"]\n\n# Print a practice plan for each day\n",
    visibleTests: ["Uses a loop", "Prints at least five lines", "Mentions each day"],
    reflectionPrompts: ["What repeated pattern did the loop remove?", "How would you add Saturday practice?"],
    teacherNotes: "Help learners see loops as a way to represent a pattern, not just a syntax requirement.",
  },
  {
    id: "lesson-functions",
    courseId: "python-beginner",
    slug: "functions",
    title: "Functions",
    summary: "Name reusable steps and pass information into them.",
    prompt: "Write a function that creates a revision message for any subject and number of minutes.",
    expectedConcepts: ["def", "parameters", "return", "function call"],
    starterCode: "def revision_message(subject, minutes):\n    # Return a helpful message\n    return \"\"\n\nprint(revision_message(\"math\", 20))\n",
    visibleTests: ["Defines a function", "Uses at least two parameters", "Calls the function"],
    reflectionPrompts: ["Why is this better as a function?", "What input would you test next?"],
    teacherNotes: "A good answer separates the message pattern from one specific example.",
  },
  {
    id: "lesson-lists",
    courseId: "python-beginner",
    slug: "lists",
    title: "Lists",
    summary: "Collect related values and work through them.",
    prompt: "Track a learner's three recent quiz scores, calculate the total, and print a short progress message.",
    expectedConcepts: ["list", "sum", "len", "loop or indexing"],
    starterCode: "scores = [68, 74, 81]\n\n# Calculate total and average\n",
    visibleTests: ["Uses a list", "Calculates an average", "Prints a progress message"],
    reflectionPrompts: ["What changes if there are five scores?", "Why is a list better than three separate variables here?"],
    teacherNotes: "Encourage students to use len(scores), not a hard-coded count.",
  },
  {
    id: "lesson-debugging",
    courseId: "python-beginner",
    slug: "debugging",
    title: "Debugging",
    summary: "Read errors and test assumptions one step at a time.",
    prompt: "Fix a broken points calculator and explain which bug you found first.",
    expectedConcepts: ["syntax errors", "logic errors", "print debugging"],
    starterCode: "points = [10, 8, 7]\nbonus = 5\n\n# This should print the total points with bonus.\ntotal = sum(points) + bonus\nprint(\"Total:\", total)\n",
    visibleTests: ["Program runs without errors", "Total includes all points", "Student explains one bug"],
    reflectionPrompts: ["What clue helped you find the issue?", "What test would catch this bug again?"],
    teacherNotes: "Require students to name the evidence they used, not only the final fix.",
  },
  {
    id: "lesson-input-output",
    courseId: "python-beginner",
    slug: "input-output",
    title: "Input and Output",
    summary: "Ask for user input and respond clearly.",
    prompt: "Build a simple greeting program that asks for a name and favorite subject, then prints a personal message.",
    expectedConcepts: ["input", "strings", "f-string", "print"],
    starterCode: "name = input(\"What is your name? \")\nsubject = input(\"Favorite subject? \")\n\n# Print a personal message\n",
    visibleTests: ["Uses input twice", "Uses both answers in output", "Output is friendly and clear"],
    reflectionPrompts: ["What could confuse a user of your program?", "How could you improve one prompt?"],
    teacherNotes: "In browser execution, input may be simulated or discussed depending on device constraints.",
  },
  {
    id: "project-study-timer",
    courseId: "python-beginner",
    slug: "study-timer",
    title: "Project: Study Timer",
    summary: "Plan focused practice blocks.",
    prompt: "Create a study timer planner that takes subjects and minutes, then prints a balanced revision schedule.",
    expectedConcepts: ["lists", "loops", "conditionals", "functions"],
    starterCode: "subjects = [\"math\", \"science\", \"python\"]\nminutes_each = 20\n\n# Build a schedule\n",
    visibleTests: ["Uses a loop", "Mentions all subjects", "Includes total minutes"],
    reflectionPrompts: ["How did you decide the schedule order?", "What would make this more useful in your school week?"],
    teacherNotes: "A strong project has clear output and avoids repeating print statements manually.",
  },
  {
    id: "project-market-calculator",
    courseId: "python-beginner",
    slug: "market-calculator",
    title: "Project: Market Calculator",
    summary: "Use Python to total everyday purchases.",
    prompt: "Build a small calculator for a market basket with item names, prices, and a total cost.",
    expectedConcepts: ["lists", "numbers", "loops", "formatting"],
    starterCode: "items = [\"beans\", \"rice\", \"soap\"]\nprices = [3500, 4200, 2500]\n\n# Print each item and the total\n",
    visibleTests: ["Prints every item", "Calculates total from prices", "Uses clear currency output"],
    reflectionPrompts: ["Where could a wrong total come from?", "How would you add one more item?"],
    teacherNotes: "The local context makes this a useful discussion of data representation and careful totals.",
  },
  {
    id: "project-quiz-game",
    courseId: "python-beginner",
    slug: "quiz-game",
    title: "Project: Quiz Game",
    summary: "Combine decisions, scorekeeping, and feedback.",
    prompt: "Create a three-question quiz that tracks a score and prints encouraging feedback.",
    expectedConcepts: ["variables", "conditionals", "scorekeeping", "functions"],
    starterCode: "score = 0\n\n# Ask or simulate three questions, update score, and print feedback\n",
    visibleTests: ["Tracks a score", "Has three questions or checks", "Prints final feedback"],
    reflectionPrompts: ["Which part controls the score?", "How could you make the quiz fairer?"],
    teacherNotes: "If input is awkward on school devices, let learners simulate answers with variables first.",
  },
];

export const courses: Course[] = [
  {
    id: "python-beginner",
    title: "Python Beginner Track",
    description: "A school-ready first Python course built around specification, dialogue, code, and reflection.",
    lessons: beginnerLessons,
  },
];

export function getLesson(lessonId: string): Lesson | undefined {
  return courses.flatMap((course) => course.lessons).find((lesson) => lesson.id === lessonId);
}

export function getDefaultLesson(): Lesson {
  return beginnerLessons[0];
}
